Add helper trait to provide type-hinting for zend-view
zendframework/zend-mvc-plugin-flashmessenger pull request #22
Opened 2018-08-11 19:16 UTC by thexpand

In favor of the following proposal:
zendframework/zend-view#102

2018-08-11 19:39 UTC, thexpand commented
@froschdesign 
I'm not sure about this one, because there is already a doc-block `@method` in `Zend\View\Renderer\PhpRenderer`. Take a look:
https://github.com/zendframework/zend-view/blob/master/src/Renderer/PhpRenderer.php#L45

2018-09-05 07:41 UTC, froschdesign requested changes

2018-09-05 07:41 UTC, froschdesign commented on src/View/HelperTrait.php
> +
Doc block with copyright and licence is missing. An example can be found here:

https://github.com/zendframework/maintainers/blob/abab4a99f3e6d1fac4d7400232ce30ee0bc95249/template/src/ConfigProvider.php#L2-L6

2018-09-05 07:41 UTC, froschdesign commented on src/View/HelperTrait.php
> + * from different Zend components can be chained afterwards.
"Zend components" is wrong, these are "Zend Framework components".

2018-09-05 07:41 UTC, froschdesign commented on src/View/HelperTrait.php
> + * Trait HelperTrait
"Trait HelperTrait" – what is this?! 😉
Can we find a short and meaningful name / description?

2018-09-05 07:41 UTC, froschdesign commented on src/View/HelperTrait.php
> + * @method FlashMessenger|PluginFlashMessenger flashMessenger($namespace = null)
We can add also the data types. See my comment here: https://github.com/zendframework/zend-i18n/pull/102#discussion_r215139655

2018-09-05 07:45 UTC, froschdesign commented
The usage of this trait must be explained in the documentation.

2018-09-05 07:58 UTC, froschdesign commented
Btw. Please use the `develop` branch for new features.

https://github.com/zendframework/zend-mvc-plugin-flashmessenger/blob/master/docs/CONTRIBUTING.md#what-branch-to-issue-the-pull-request-against

2018-09-05 12:30 UTC, thexpand commented
@froschdesign 
I suggest adding the docs as a sub-section of the main section `View Helper`.
Maybe at the bottom?
See more about the naming in my comment here: https://github.com/zendframework/zend-i18n/pull/102#issuecomment-418711168
Here's a link to the main section in the docs: https://docs.zendframework.com/zend-mvc-plugin-flashmessenger/flash-messenger-view-helper/

2018-09-05 16:03 UTC, froschdesign commented
@thexpand 
> Maybe at the bottom?

For this single page is bottom okay.

2018-09-05 19:40 UTC, froschdesign commented on src/View/HelperTrait.php
> + * @copyright Copyright (c) 2005-2018 Zend Technologies USA Inc. (http://www.zend.com)
Please use for new files only the current year.

2018-09-12 18:38 UTC, thexpand commented
@froschdesign 
I've placed the docs at the bottom, without block quotes, in contrast to the other PRs (https://github.com/zendframework/zend-i18n/pull/102, https://github.com/zendframework/zend-form/pull/217)

2019-10-19 21:39 UTC, michalbundyra approved these changes

2019-10-19 21:48 UTC, merged

2019-10-19 21:49 UTC, webimpress commented
Thanks, @thexpand!